### ISSUE TITLE
Call to a member function rewrite() on null

### ISSUE THREAD

**Issue by geek-merlin** [drupal-composer/info-rewrite#6]
Huh this broke my composer.
```
$ composer require drupal/drush_language
Using version ^1.5 for drupal/drush_language
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/drush_language (1.5.0): Downloading (100%)         
PHP Fatal error:  Uncaught Error: Call to a member function rewrite() on null in phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:123
Stack trace:
#0 phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(91): DrupalComposer\Composer\DrupalInfo_composer_tmp3->doWriteInfoFiles(Object(Composer\Package\CompletePackage))
#1 [internal function]: DrupalComposer\Composer\DrupalInfo_composer_tmp3->writeInfoFiles(Object(Composer\Installer\PackageEvent))
#2 phar:///home/merlin/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#3 phar:///home/merlin/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#4 phar:///home/merlin/bin/composer/src/Composer/Installer.php(609): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-in...', true, Object(Compose in phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 123

Fatal error: Uncaught Error: Call to a member function rewrite() on null in phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:123
Stack trace:
#0 phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(91): DrupalComposer\Composer\DrupalInfo_composer_tmp3->doWriteInfoFiles(Object(Composer\Package\CompletePackage))
#1 [internal function]: DrupalComposer\Composer\DrupalInfo_composer_tmp3->writeInfoFiles(Object(Composer\Installer\PackageEvent))
#2 phar:///home/merlin/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#3 phar:///home/merlin/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#4 phar:///home/merlin/bin/composer/src/Composer/Installer.php(609): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-in...', true, Object(Compose in phar:///home/merlin/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 123

```

**Comment by geek-merlin** [comment]
That error prevented even removing. Used the sledgehammer:
```
$ rm -rf vendor/drupal-composer/info-rewrite
$ composer remove drupal-composer/info-rewrite

```

**Comment by jhedstrom** [comment]
This only appears to happen on D7 projects. Digging in now.

**Comment by jhedstrom** [comment]
This should be resolved in the latest release.
